### ISSUE TITLE
Compiling error with esp32 board

### ISSUE THREAD

**Issue by tackelua** [marcmerlin/NewLiquidCrystal#3] opened 2018-01-03 06:57 UTC
I try HelloWorld_i2c with ESP32 Dev Module
Error
`Compiling 'HelloWorld_i2c' for 'ESP32 Dev Module'
LiquidCrystal.cpp: In member function virtual void LiquidCrystal::setBacklight(uint8_t)
 
LiquidCrystal.cpp: 190:48: error: 'analogWrite' was not declared in this scope
   analogWrite ( _backlightPin, value )
 
Error compiling libraries
Build failed for project 'HelloWorld_i2c'
LiquidCrystal.cpp: 194:54: error: 'analogWrite' was not declared in this scope
   analogWrite ( _backlightPin, 255 - value )`

It's error because it cannot found <WProgram.h> or <Arduino.h> in LiquidCrystal.cpp
Remember: I try HelloWorld_I2C,
If I choose original arduino board or esp8266, it's okay. But error with esp32
Please check it.

**Comment by mcquaas** [comment] 2018-09-15 18:50
Same problem here, following https://forum.arduino.cc/index.php?topic=128635.0

**Comment by marcmerlin** [comment] 2018-12-10 03:52
Sorry, for some reason I never got an Email for this. My apologies.
Can you confirm that it works on ESP32 when you comment out these lines?
Can you confirm which line(s) exactly, or better, submit a pull request?

**Comment by marcmerlin** [comment] 2018-12-14 21:04
Ah, I missed that it's the I2C code which I didn't write and don't use. I only wrote the _SR driver in this fork.
You should try the upstream project for I2C issues: https://bitbucket.org/fmalpartida/new-liquidcrystal/wiki/Home

**Comment by marcmerlin** [comment] 2018-12-14 21:05
duplicate of #1  
closing

**Closed as completed by marcmerlin** 2018-12-14 21:05 UTC
